### ISSUE TITLE
allfinal throws a warning for lambda streams params

### ISSUE THREAD

**Issue by ccostin93** [iwillfailyou/service#14]
Taking the following case:

```
final List<String> strings = new Arraylist<String>();
strings.stream().forEach(string -> processString(string));
```

allfinal will throw a warning of `string`.

**Comment by nikialeksey** [comment]
I'm working on settings for `allfinal` for such cases. By default, I think, it will be disabled, because lambda parameter can be reassigned in lambda. For now you can rewrite all lambda params with final:

```java
strings.stream().forEach((final String string) -> processString(string));
```

**Comment by nikialeksey** [comment]
I just updated the version of plugins (0.1.1 and higher support the allfinal.skipLambdaParams settings, which can be used to skip `final` in lambda params). See the description https://github.com/iwillfailyou/service#allfinal
