### ISSUE TITLE
Skip test code from iwfy validation

### ISSUE THREAD

**Issue by ccostin93** [iwillfailyou/service#18]
Have you considered the option to skip test code from the iwfy validation?

PMD also offers this feature: https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html#includeTests

By default, test code should be included.
This feature won't really help with new projects, but it will make the "migration-phase" for older ones a little easier, as the devs can see just the issues in the prod code and not be blinded by issues in their test code.

**Comment by nikialeksey** [comment]
Yes! I think, some of inspections can be valid for the tests classes, because we want readable tests. May be some of inspections can be skipped for tests. What if we do settings for each inspection skip or not test classes? Even more general: skip or not files by pattern?

**Comment by ccostin93** [comment]
@nikialeksey I do like the idea of file selection/skip by regex pattern. It's way more scalable.
But I would consider this a global setting rather than for each rule.

I would maybe also consider a flag to enable a specific rule. Not sure if I missed something, but there is no way to disable a specific rule. The best you can do is put an insanely high threshold.

In an older project, when we added PMD, we basically disabled all rules and then had a ticket to enable each rule and fix the code. I think such an option is quite good for initial adoption. You can setup iwfy plugin and then create a ticket for each rule.

**Comment by nikialeksey** [comment]
@ccostin93 Thanks, I've just created #19 about disabling rules. 

About patterns for skipping files: I think, we can make global settings and local settings, and local would have higher priority

**Comment by nikialeksey** [comment]
I've just released a new version of plugins (`0.2.0`), which support disabling inspections.

**Comment by nikialeksey** [comment]
I've just release a new version of plugins (0.4.+),  which [support exclusion patterns](https://github.com/iwillfailyou/service#excluding-files-from-inspects)
